%%
%min COM traj control input
Cost_minCOM_control=classdef_CostPart(eye(MPC_inputs.N),[],zeros(N,1),0);

% min com vel to ref
xCost_minCOM_VelToRef=classdef_CostPart(COM_state_preview.Pu_dc,[],COM_state_preview.f_dc(:,1),MPC_inputs.dc_ref(:,1));
yCost_minCOM_VelToRef=classdef_CostPart(COM_state_preview.Pu_dc,[],COM_state_preview.f_dc(:,2),MPC_inputs.dc_ref(:,2));

% min mean CoP to ref
xCost_minZMPmean_PosToRef=classdef_CostPart(CoP_state_preview.Pu_z_mean,...
    Step_state_preview.Pu_step,...
    CoP_state_preview.f_z_mean(:,1),...
    Step_state_preview.f_step(:,1)+MPC_inputs.translate_step_cop_ref(1,1)...
    );

yCost_minZMPmean_PosToRef=classdef_CostPart(CoP_state_preview.Pu_z_mean,...
    Step_state_preview.Pu_step,...
    CoP_state_preview.f_z_mean(:,2),...
    Step_state_preview.f_step(:,2)+(MPC_inputs.left_support-MPC_inputs.right_support)*MPC_inputs.translate_step_cop_ref(1,2)...
    );

% min COM height to ref
hcom_ref_max_reduce=hcom_ref_max(preview_windows,:);

zCost_minCOM_HeightToRef=classdef_CostPart(COM_state_preview.Pu_c,...
    [],...
    COM_state_preview.f_c(:,3),...
    hcom_ref_max_reduce...
    );

%% Concatenate Cost function independently along each axis
xH=OptimCostWeight(1)*blkdiag(Cost_minCOM_control.H,zeros(size(Step_state_preview.Pu_step,2)))...
    +OptimCostWeight(2)*blkdiag(xCost_minCOM_VelToRef.H,zeros(size(Step_state_preview.Pu_step,2)))...
    +OptimCostWeight(3)*xCost_minZMPmean_PosToRef.H;

xf=OptimCostWeight(1)*[Cost_minCOM_control.f;zeros(size(Step_state_preview.Pu_step,2),1)]...
    +OptimCostWeight(2)*[xCost_minCOM_VelToRef.f;zeros(size(Step_state_preview.Pu_step,2),1)]...
    +OptimCostWeight(3)*xCost_minZMPmean_PosToRef.f;

yH=OptimCostWeight(1)*blkdiag(Cost_minCOM_control.H,zeros(size(Step_state_preview.Pu_step,2)))...
    +OptimCostWeight(2)*blkdiag(yCost_minCOM_VelToRef.H,zeros(size(Step_state_preview.Pu_step,2)))...
    +OptimCostWeight(3)*yCost_minZMPmean_PosToRef.H;

yf=OptimCostWeight(1)*[Cost_minCOM_control.f;zeros(size(Step_state_preview.Pu_step,2),1)]...
    +OptimCostWeight(2)*[yCost_minCOM_VelToRef.f;zeros(size(Step_state_preview.Pu_step,2),1)]...
    +OptimCostWeight(3)*yCost_minZMPmean_PosToRef.f;

zH=OptimCostWeight(1)*Cost_minCOM_control.H...
    +OptimCostWeight(4)*zCost_minCOM_HeightToRef.H;

zf=OptimCostWeight(1)*Cost_minCOM_control.f...
    +OptimCostWeight(4)*zCost_minCOM_HeightToRef.f;

%% Concatenate Cost function along all axis
H=blkdiag(xH,yH);
H=blkdiag(H,zH);

f=[xf;yf;zf];
