function [A,b]=function_constraint_convexhull(...
    Pu_up,Pu_down,Pu_step,...
    xf_up,xf_down,xf_step,...
    yf_up,yf_down,yf_step,...
    no_double_support,double_support,right_support,left_support,...
    fronttoankle,backtoankle,inttoankle,exttoankle,sole_margin,...
    theta)
%compute linear matrix to verify in a quadprog optimization
%Ax<b
%%
if isempty(theta)
    theta=zeros(size(Pu_up,1),1);
end

dx=[cos(theta(no_double_support,:)) -sin(theta(no_double_support,:)) -cos(theta(no_double_support,:)) sin(theta(no_double_support,:))];
dy=[sin(theta(no_double_support,:)) cos(theta(no_double_support,:)) -sin(theta(no_double_support,:)) -cos(theta(no_double_support,:))];

dx_=[cos(theta(double_support,:)) -sin(theta(double_support,:)) -cos(theta(double_support,:)) sin(theta(double_support,:))];
dy_=[sin(theta(double_support,:)) cos(theta(double_support,:)) -sin(theta(double_support,:)) -cos(theta(double_support,:))];

if isempty(Pu_step)
        xA_temp=[diag(dx(:,1))*Pu_up(no_double_support,:);...
            diag(dx(:,3))*Pu_up(no_double_support,:);...
            diag(dx(:,1))*Pu_down(no_double_support,:);...
            diag(dx(:,3))*Pu_down(no_double_support,:);...
            diag(dx_(:,1))*Pu_up(double_support,:);...
            diag(dx_(:,3))*Pu_up(double_support,:);...
            diag(dx_(:,1))*Pu_down(double_support,:);...
            diag(dx_(:,3))*Pu_down(double_support,:)];
        
        xA_temp=[xA_temp;...
            diag(dx(:,2))*Pu_up(no_double_support,:);...
            diag(dx(:,4))*Pu_up(no_double_support,:);...
            diag(dx(:,2))*Pu_down(no_double_support,:);...
            diag(dx(:,4))*Pu_down(no_double_support,:);...
            diag(dx_(:,2))*Pu_up(double_support,:);...
            diag(dx_(:,4))*Pu_up(double_support,:);...
            diag(dx_(:,2))*Pu_down(double_support,:);...
            diag(dx_(:,4))*Pu_down(double_support,:)];
        
        yA_temp=[diag(dy(:,1))*Pu_up(no_double_support,:);...
            diag(dy(:,3))*Pu_up(no_double_support,:);...
            diag(dy(:,1))*Pu_down(no_double_support,:);...
            diag(dy(:,3))*Pu_down(no_double_support,:);...
            diag(dy_(:,1))*Pu_up(double_support,:);...
            diag(dy_(:,3))*Pu_up(double_support,:);...
            diag(dy_(:,1))*Pu_down(double_support,:);...
            diag(dy_(:,3))*Pu_down(double_support,:)];
        
        yA_temp=[yA_temp;...
            diag(dy(:,2))*Pu_up(no_double_support,:);...
            diag(dy(:,4))*Pu_up(no_double_support,:);...
            diag(dy(:,2))*Pu_down(no_double_support,:);...
            diag(dy(:,4))*Pu_down(no_double_support,:);...
            diag(dy_(:,2))*Pu_up(double_support,:);...
            diag(dy_(:,4))*Pu_up(double_support,:);...
            diag(dy_(:,2))*Pu_down(double_support,:);...
            diag(dy_(:,4))*Pu_down(double_support,:)];
  
else
        xA_temp=[diag(dx(:,1))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,3))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,1))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,3))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx_(:,1))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,3))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,1))*[Pu_down(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,3))*[Pu_down(double_support,:) -Pu_step(double_support,:)]];
        
        xA_temp=[xA_temp;...
            diag(dx(:,2))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,4))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,2))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx(:,4))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dx_(:,2))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,4))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,2))*[Pu_down(double_support,:) -Pu_step(double_support,:)];...
            diag(dx_(:,4))*[Pu_down(double_support,:) -Pu_step(double_support,:)]];
        
        yA_temp=[diag(dy(:,1))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,3))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,1))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,3))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy_(:,1))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,3))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,1))*[Pu_down(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,3))*[Pu_down(double_support,:) -Pu_step(double_support,:)]];
        
        yA_temp=[yA_temp;...
            diag(dy(:,2))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,4))*[Pu_up(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,2))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy(:,4))*[Pu_down(no_double_support,:) -Pu_step(no_double_support,:)];...
            diag(dy_(:,2))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,4))*[Pu_up(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,2))*[Pu_down(double_support,:) -Pu_step(double_support,:)];...
            diag(dy_(:,4))*[Pu_down(double_support,:) -Pu_step(double_support,:)]];

        
end

A_temp_=[xA_temp yA_temp];

xb_=[no_double_support(no_double_support)*(fronttoankle-sole_margin);...
        no_double_support(no_double_support)*(backtoankle-sole_margin);...
        no_double_support(no_double_support)*(fronttoankle-sole_margin);...
        no_double_support(no_double_support)*(backtoankle-sole_margin)]+...
        [dx(:,1).*(xf_step(no_double_support,:)-xf_up(no_double_support,:));...
        dx(:,3).*(xf_step(no_double_support,:)-xf_up(no_double_support,:));...
        dx(:,1).*(xf_step(no_double_support,:)-xf_down(no_double_support,:));...
        dx(:,3).*(xf_step(no_double_support,:)-xf_down(no_double_support,:))];
xb_=[xb_;...
        [double_support(double_support)*(fronttoankle-sole_margin);...
        double_support(double_support)*(backtoankle-sole_margin);...
        double_support(double_support)*(fronttoankle-sole_margin);...
        double_support(double_support)*(backtoankle-sole_margin)]+...
        [dx_(:,1).*(xf_step(double_support,:)-xf_up(double_support,:));...
        dx_(:,3).*(xf_step(double_support,:)-xf_up(double_support,:));...
        dx_(:,1).*(xf_step(double_support,:)-xf_down(double_support,:));...
        dx_(:,3).*(xf_step(double_support,:)-xf_down(double_support,:))]];
xb_=[xb_;...
        [dx(:,2).*(xf_step(no_double_support,:)-xf_up(no_double_support,:));...
        dx(:,4).*(xf_step(no_double_support,:)-xf_up(no_double_support,:));...
        dx(:,2).*(xf_step(no_double_support,:)-xf_down(no_double_support,:));...
        dx(:,4).*(xf_step(no_double_support,:)-xf_down(no_double_support,:))]];
xb_=[xb_;...
        [dx_(:,2).*(xf_step(double_support,:)-xf_up(double_support,:));...
        dx_(:,4).*(xf_step(double_support,:)-xf_up(double_support,:));...
        dx_(:,2).*(xf_step(double_support,:)-xf_down(double_support,:));...
        dx_(:,4).*(xf_step(double_support,:)-xf_down(double_support,:))]];

yb_=[dy(:,1).*(yf_step(no_double_support,:)-yf_up(no_double_support,:));...
        dy(:,3).*(yf_step(no_double_support,:)-yf_up(no_double_support,:));...
        dy(:,1).*(yf_step(no_double_support,:)-yf_down(no_double_support,:));...
        dy(:,3).*(yf_step(no_double_support,:)-yf_down(no_double_support,:))];
yb_=[yb_;...
        [dy_(:,1).*(yf_step(double_support,:)-yf_up(double_support,:));...
        dy_(:,3).*(yf_step(double_support,:)-yf_up(double_support,:));...
        dy_(:,1).*(yf_step(double_support,:)-yf_down(double_support,:));...
        dy_(:,3).*(yf_step(double_support,:)-yf_down(double_support,:))]];
yb_=[yb_;...
        [right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
        right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin);...
        right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
        right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin)]+...
        [dy(:,2).*(yf_step(no_double_support,:)-yf_up(no_double_support,:));...
        dy(:,4).*(yf_step(no_double_support,:)-yf_up(no_double_support,:));...
        dy(:,2).*(yf_step(no_double_support,:)-yf_down(no_double_support,:));...
        dy(:,4).*(yf_step(no_double_support,:)-yf_down(no_double_support,:))]];
yb_=[yb_;...
        [double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2]+...
        [dy_(:,2).*(yf_step(double_support,:)-yf_up(double_support,:));...
        dy_(:,4).*(yf_step(double_support,:)-yf_up(double_support,:));...
        dy_(:,2).*(yf_step(double_support,:)-yf_down(double_support,:));...
        dy_(:,4).*(yf_step(double_support,:)-yf_down(double_support,:))]];
    
b_temp_=xb_+yb_;

A=A_temp_;
b=b_temp_;

% %% Constraint ZMP in convex hull
%     if isempty(Pu_step)
%         A_temp=[Pu_up(no_double_support,:);...
%             -Pu_up(no_double_support,:);...
%             Pu_down(no_double_support,:);...
%             -Pu_down(no_double_support,:)];
%     else
%         A_temp=[Pu_up(no_double_support,:) -Pu_step(no_double_support,:);...
%             -Pu_up(no_double_support,:) Pu_step(no_double_support,:);...
%             Pu_down(no_double_support,:) -Pu_step(no_double_support,:);...
%             -Pu_down(no_double_support,:) Pu_step(no_double_support,:)];
%     end
%     if isempty(Pu_step)
%         A_temp=[A_temp;...
%             Pu_up(double_support,:);...
%             -Pu_up(double_support,:);...
%             Pu_down(double_support,:);...
%             -Pu_down(double_support,:)];
%     else
%         A_temp=[A_temp;...
%             Pu_up(double_support,:) -Pu_step(double_support,:);...
%             -Pu_up(double_support,:) Pu_step(double_support,:);...
%             Pu_down(double_support,:) -Pu_step(double_support,:);...
%             -Pu_down(double_support,:) Pu_step(double_support,:)];
%     end
%     
%     
%     xb=[no_double_support(no_double_support)*(fronttoankle-sole_margin);...
%         no_double_support(no_double_support)*(backtoankle-sole_margin);...
%         no_double_support(no_double_support)*(fronttoankle-sole_margin);...
%         no_double_support(no_double_support)*(backtoankle-sole_margin)]...
%         +[xf_step(no_double_support,:)-xf_up(no_double_support,:);...
%         -xf_step(no_double_support,:)+xf_up(no_double_support,:);...
%         xf_step(no_double_support,:)-xf_down(no_double_support,:);...
%         -xf_step(no_double_support,:)+xf_down(no_double_support,:)];
%     
%     yb=[right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
%         right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin);...
%         right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
%         right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin)]...
%         +[yf_step(no_double_support,:)-yf_up(no_double_support,:);...
%         -yf_step(no_double_support,:)+yf_up(no_double_support,:);...
%         yf_step(no_double_support,:)-yf_down(no_double_support,:);...
%         -yf_step(no_double_support,:)+yf_down(no_double_support,:)];
%     
%     xb=[xb;...
%         [double_support(double_support)*(fronttoankle-sole_margin);...
%         double_support(double_support)*(backtoankle-sole_margin);...
%         double_support(double_support)*(fronttoankle-sole_margin);...
%         double_support(double_support)*(backtoankle-sole_margin)]+...
%         [xf_step(double_support,:)-xf_up(double_support,:);...
%         -xf_step(double_support,:)+xf_up(double_support,:);...
%         xf_step(double_support,:)-xf_down(double_support,:);...
%         -xf_step(double_support,:)+xf_down(double_support,:)]];
%     
%     yb=[yb;...
%         [double_support(double_support)*(exttoankle-sole_margin)*2;...
%         double_support(double_support)*(exttoankle-sole_margin)*2;...
%         double_support(double_support)*(exttoankle-sole_margin)*2;...
%         double_support(double_support)*(exttoankle-sole_margin)*2]+...
%         [yf_step(double_support,:)-yf_up(double_support,:);...
%         -yf_step(double_support,:)+yf_up(double_support,:);...
%         yf_step(double_support,:)-yf_down(double_support,:);...
%         -yf_step(double_support,:)+yf_down(double_support,:)]];
%     
%     A=blkdiag(A_temp,A_temp);
%     b=[xb;yb];