function [A,b]=function_constraint_convexhull(...
    Pu_up,Pu_down,Pu_step,...
    xf_up,xf_down,xf_step,...
    yf_up,yf_down,yf_step,...
    no_double_support,double_support,right_support,left_support,...
    fronttoankle,backtoankle,inttoankle,exttoankle,sole_margin)
%compute linear matrix to verify in a quadprog optimization
%Ax<b
%% Constraint ZMP in convex hull
    if isempty(Pu_step)
        A_temp=[Pu_up(no_double_support,:);...
            -Pu_up(no_double_support,:);...
            Pu_down(no_double_support,:);...
            -Pu_down(no_double_support,:)];
    else
        A_temp=[Pu_up(no_double_support,:) -Pu_step(no_double_support,:);...
            -Pu_up(no_double_support,:) Pu_step(no_double_support,:);...
            Pu_down(no_double_support,:) -Pu_step(no_double_support,:);...
            -Pu_down(no_double_support,:) Pu_step(no_double_support,:)];
    end
    if isempty(Pu_step)
        A_temp=[A_temp;...
            Pu_up(double_support,:);...
            -Pu_up(double_support,:);...
            Pu_down(double_support,:);...
            -Pu_down(double_support,:)];
    else
        A_temp=[A_temp;...
            Pu_up(double_support,:) -Pu_step(double_support,:);...
            -Pu_up(double_support,:) Pu_step(double_support,:);...
            Pu_down(double_support,:) -Pu_step(double_support,:);...
            -Pu_down(double_support,:) Pu_step(double_support,:)];
    end
    
    
    xb=[no_double_support(no_double_support)*(fronttoankle-sole_margin);...
        no_double_support(no_double_support)*(backtoankle-sole_margin);...
        no_double_support(no_double_support)*(fronttoankle-sole_margin);...
        no_double_support(no_double_support)*(backtoankle-sole_margin)]...
        +[xf_step(no_double_support,:)-xf_up(no_double_support,:);...
        -xf_step(no_double_support,:)+xf_up(no_double_support,:);...
        xf_step(no_double_support,:)-xf_down(no_double_support,:);...
        -xf_step(no_double_support,:)+xf_down(no_double_support,:)];
    
    yb=[right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
        right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin);...
        right_support(no_double_support)*(inttoankle-sole_margin)+left_support(no_double_support)*(exttoankle-sole_margin);...
        right_support(no_double_support)*(exttoankle-sole_margin)+left_support(no_double_support)*(inttoankle-sole_margin)]...
        +[yf_step(no_double_support,:)-yf_up(no_double_support,:);...
        -yf_step(no_double_support,:)+yf_up(no_double_support,:);...
        yf_step(no_double_support,:)-yf_down(no_double_support,:);...
        -yf_step(no_double_support,:)+yf_down(no_double_support,:)];
    
    xb=[xb;...
        [double_support(double_support)*(fronttoankle-sole_margin);...
        double_support(double_support)*(backtoankle-sole_margin);...
        double_support(double_support)*(fronttoankle-sole_margin);...
        double_support(double_support)*(backtoankle-sole_margin)]+...
        [xf_step(double_support,:)-xf_up(double_support,:);...
        -xf_step(double_support,:)+xf_up(double_support,:);...
        xf_step(double_support,:)-xf_down(double_support,:);...
        -xf_step(double_support,:)+xf_down(double_support,:)]];
    
    yb=[yb;...
        [double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2;...
        double_support(double_support)*(exttoankle-sole_margin)*2]+...
        [yf_step(double_support,:)-yf_up(double_support,:);...
        -yf_step(double_support,:)+yf_up(double_support,:);...
        yf_step(double_support,:)-yf_down(double_support,:);...
        -yf_step(double_support,:)+yf_down(double_support,:)]];
    
    A=blkdiag(A_temp,A_temp);
    b=[xb;yb];